    Consider the below code to answer further questions:

In [1]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']

array_list = np.array(object = list_)

In [2]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

Q.No-01    Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

Ans :-

In [3]:
print("Data type of 'list_':", type(list_))
print("Data type of 'array_list':", type(array_list))

Data type of 'list_': <class 'list'>
Data type of 'array_list': <class 'numpy.ndarray'>


Yes, there is a difference in the data type of the variables `list_` and `array_list`.

In Python, the variable `list_` is a standard Python list, which can hold elements of any data type, including strings, integers, floats, etc.

On the other hand, `array_list` is a NumPy array created from the `list_` variable. NumPy arrays are homogeneous arrays, which means all elements in the array must have the same data type. In this case, since the elements in the `list_` variable are strings, the NumPy array will automatically convert them to strings, and all elements in `array_list` will be of type `numpy.str_`.

--------------------------------------------------------------------------------------------------------------------

Q.No-02    Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

Ans :-

In [4]:
print("Data types of elements in 'list_':")
for element in list_:
    print(type(element))

print("\nData types of elements in 'array_list':")
for element in array_list:
    print(type(element))

Data types of elements in 'list_':
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in 'array_list':
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


--------------------------------------------------------------------------------------------------------------------

Q.No-03    Considering the following changes in the variable, array_list:
```python
array_list = np.array(object = list_, dtype = int)
```
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

Ans :-

Yes, there will be a difference in the data type of the elements present in both variables `list_` and `array_list` after making the change 

In [5]:
array_list = np.array(object = list_, dtype = int)

In [6]:
print("Data types of elements in 'list_':")
for element in list_:
    print(type(element))

print("\nData types of elements in 'array_list':")
for element in array_list:
    print(type(element))

Data types of elements in 'list_':
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in 'array_list':
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


In the original code, when the `np.array()` function was used without specifying the `dtype`, NumPy inferred the data type of the elements in the `list_` based on the values provided in the list. Since the values were represented as strings (e.g., '1', '2', '3', etc.), NumPy considered them as strings and created an array of string data type.

However, when the `dtype=int` argument is provided, it explicitly sets the data type of the elements in the `array_list` as integers. As a result, the elements in `array_list` will be converted to integers.

--------------------------------------------------------------------------------------------------------------------

Consider the below code to answer further questions:

In [7]:
import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

In [8]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

Q.No-04   Write a code to find the following characteristics of variable, num_array:

    (i) shape

    (ii) size

Ans :-

    (i) Shape of the num_array

In [9]:
shape_of_array = num_array.shape
print("Shape of num_array:", shape_of_array)

Shape of num_array: (2, 3)


    (ii) Size of the num_array

In [10]:
size_of_array = num_array.size
print("Size of num_array:", size_of_array)

Size of num_array: 6


--------------------------------------------------------------------------------------------------------------------

Q.No-05    Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.

    [Hint: The size of the array will be 9 and the shape will be (3,3).]

Ans :-

In [11]:
import numpy as np

In [12]:
Zero_array = np.zeros((3,3))

In [13]:
Zero_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

--------------------------------------------------------------------------------------------------------------------

Q.No-06    Create an identity matrix of shape (5,5) using numpy functions?

    [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

Ans :-

In [35]:
import numpy.matlib as nm

Identity_matrix = nm.eye(5)

Identity_matrix

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

                                        END                                        